### ISSUE TITLE
Could this be a directive?

### ISSUE THREAD

**Issue by dougalg** [wovue/focus-trap#2]
IMO this would be great as a directive like `:trap-focus="active"`, rather than a component. What do you think? It would allow less DOM nesting, and markup.

**Comment by dougalg** [comment]
Actually, given the complexity, maybe a mixin would make more sense

**Comment by wochap** [comment]
Sorry, given the complexity, it can't be a directive,  i'm not sure about mixins, [mixins introduce implicit dependencies](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#mixins-introduce-implicit-dependencies).
